### ISSUE TITLE
respawn

### ISSUE THREAD

**Issue by Cart00nHead** [Toly65/UdonCombatSystem#10]
Hey sorry to bother you again 

so I'm having an issue where the first time you die everything works fine
but after that you skip going to the death box and go straight to respawn but your body gets stuck behind any terrain/buildings between you and the respawn. you then can only move in one direction towards where your body had been stuck

any help / advice would be greatly appreciated :)
cheers CH

**Comment by Toly65** [comment]
the issue is that are 3 different issues stacking on top of each other.
1. VRchat's networking is slow and thus the system puts players in a little box to allow all the damage to be applied
2. for some mystical reason, it doesn't do number 1
3. your issue, probably because of number 2 causing multiple teleports to happen within the same frame

I'm working on the system right now as it's had a fit for the millionth time now, but no matter how much I try to unravel those 3 issues in a trench coat, being one big issue it doesn't wanna play nice, the simplest solution would be to remove the death box system entirely, but that requires having some other way of making sure players don't spawn with less than max health

This can be done externally by you if the players are spawning in something like a lobby, with their health being hidden till the start of the next match, and their health is maxed out at that point instead of directly at respawn,

The health manager has an option to straight-up disable the respawn box if deemed necessary, but of course, it's recommended to do the above if you decide to do that.

**Comment by Cart00nHead** [comment]
Thanks for getting back to me

I understand, that's definitely frustrating I feel your pain. I wish i could help out but you are far more talented than me 😅
I only just started learning coding myself 

it seems disabling the respawn box doesn't help with my issue of getting trapped behind stuff. could it be like you mentioned above trying to teleport to far in to such a short time frame?

also so what your saying is the problem is damage being dealt after respawn?. so in theory if the HP is maxed at 100 i could then heal players 100 a few seconds after respawn? to make sure all new players are at max HP?

I know its probably a lot harder than that though 😅

**Comment by Cart00nHead** [comment]
It seems disabling the respawn box doesn't help with my issue of getting trapped behind stuff.

after doing a little research it appears its a common bug with localPLayer.TeleportTo 
the solution seems to be adding a sendcustomeventdelayed to give it time to catch up

**Comment by Cart00nHead** [comment]
that made it work fine, however it still suffered from the issue you mentioned taking delayed damage causing you to not have full hp on respawn 
adding a second delay before you heal seems to have fixed all the issues ( 99% sure anyway) i have only tested it locally 

	Debug.Log("respawn Triggerd");
        localPLayer.TeleportTo(RespawnPoint.position, RespawnPoint.rotation);
        CurrentHunger = 100.0f;
        SendCustomEventDelayedSeconds("RespawnHealth", 0.1f);
		CurrentHealth = RespawnHealth;
        //localPLayer.CombatSetCurrentHitpoints(RespawnHealth);
        Dead = false;
