### ISSUE TITLE
Health visuals 

### ISSUE THREAD

**Issue by SolidGlade** [Toly65/UdonCombatSystem#7]
The green health bar doesn't go down when taking damage,

I am very sorry. it would appear the combat system was working, the issue was the health bar not going down
is there anyway to fix this

**Comment by Toly65** [comment]
make sure that the health bar image itself is set to filled image type
<img width="693" alt="image" src="https://user-images.githubusercontent.com/88860967/152675876-ec3ed9ef-aa2b-4a5a-a10c-c2acecb978a8.png">
and make sure the stat manager has everything assigned to something
<img width="692" alt="image" src="https://user-images.githubusercontent.com/88860967/152675898-1d01b28b-02fb-458b-b768-67a4c4abe43e.png">
because for some reason I haven't thought to put a null checker in the stat manager since it's bodged as hell

**Comment by SolidGlade** [comment]
That's done the trick thankyou very much sir :)
